services:
  pg-static-build-x86_64:
    container_name: pg-static-build-x86_64-${PG_VERSION:-16.1} # Very important to add the version to the name for caching tricks
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PG_VERSION: ${PG_VERSION:-16.1}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    image: pg-static-build-x86_64
    platform: linux/amd64
    volumes:
      - ${PWD}/bins/x86_64:/output

  pg-static-build-x86:
    container_name: pg-static-build-x86-${PG_VERSION:-16.1} # Very important to add the version to the name for caching tricks
    build:
      context: .
      dockerfile: Dockerfile.x86
      args:
        PG_VERSION: ${PG_VERSION:-16.1}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    image: pg-static-build-x86
    platform: linux/386
    volumes:
      - ${PWD}/bins/x86:/output

  pg-static-build-arm64:
    container_name: pg-static-build-arm64-${PG_VERSION:-16.1} # Very important to add the version to the name for caching tricks
    build:
      context: .
      dockerfile: Dockerfile.arm64
      args:
        PG_VERSION: ${PG_VERSION:-16.1}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    image: pg-static-build-arm64
    platform: linux/arm64
    volumes:
      - ${PWD}/bins/arm64:/output

  pg-static-build-arm32:
    container_name: pg-static-build-arm32-${PG_VERSION:-16.1} # Very important to add the version to the name for caching tricks
    build:
      context: .
      dockerfile: Dockerfile.arm32
      args:
        PG_VERSION: ${PG_VERSION:-16.1}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    image: pg-static-build-arm32
    platform: linux/arm/v7
    volumes:
      - ${PWD}/bins/arm32:/output