services:
  pg-static-build-x86_64:
    container_name: pg-static-build-x86_64-${PG_VERSION:-16.1}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PG_VERSION: ${PG_VERSION:-16.1}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        TARGETARCH: ${TARGETARCH:-x86_64}
      cache_from:
        - type=gha,scope=pg-static-build-x86_64
      cache_to:
        - type=gha,mode=max,scope=pg-static-build-x86_64
    image: pg-static-build-x86_64
    platform: linux/amd64
    volumes:
      - ./bins/x86_64:/output

  pg-static-build-x86:
    container_name: pg-static-build-x86-${PG_VERSION:-16.1}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PG_VERSION: ${PG_VERSION:-16.1}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        TARGETARCH: ${TARGETARCH:-x86}
      cache_from:
        - type=gha,scope=pg-static-build-x86
      cache_to:
        - type=gha,mode=max,scope=pg-static-build-x86
    image: pg-static-build-x86
    platform: linux/386
    volumes:
      - ./bins/x86:/output

  pg-static-build-arm64:
    container_name: pg-static-build-arm64-${PG_VERSION:-16.1}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PG_VERSION: ${PG_VERSION:-16.1}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        TARGETARCH: ${TARGETARCH:-arm64}
      cache_from:
        - type=gha,scope=pg-static-build-arm64
      cache_to:
        - type=gha,mode=max,scope=pg-static-build-arm64
    image: pg-static-build-arm64
    platform: linux/arm64
    volumes:
      - ./bins/arm64:/output

  pg-static-build-arm32:
    container_name: pg-static-build-arm32-${PG_VERSION:-16.1}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PG_VERSION: ${PG_VERSION:-16.1}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        TARGETARCH: ${TARGETARCH:-arm32}
      cache_from:
        - type=gha,scope=pg-static-build-arm32
      cache_to:
        - type=gha,mode=max,scope=pg-static-build-arm32
    image: pg-static-build-arm32
    platform: linux/arm/v7
    volumes:
      - ./bins/arm32:/output