services:
  tmux-static-build-x86_64:
    container_name: tmux-static-build-x86_64-${TMUX_VERSION:-3.6b}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TMUX_VERSION: ${TMUX_VERSION:-3.6b}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
      cache_from:
        - type=gha,scope=tmux-static-build-x86_64
      cache_to:
        - type=gha,mode=max,scope=tmux-static-build-x86_64
    image: tmux-static-build-x86_64
    platform: linux/amd64
    volumes:
      - ./bins/x86_64:/output
    networks:
      - tmux_default

  tmux-static-build-x86:
    container_name: tmux-static-build-x86-${TMUX_VERSION:-3.6b}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TMUX_VERSION: ${TMUX_VERSION:-3.6b}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
      cache_from:
        - type=gha,scope=tmux-static-build-x86
      cache_to:
        - type=gha,mode=max,scope=tmux-static-build-x86
    image: tmux-static-build-x86
    platform: linux/386
    volumes:
      - ./bins/x86:/output
    networks:
      - tmux_default

  tmux-static-build-arm64:
    container_name: tmux-static-build-arm64-${TMUX_VERSION:-3.6b}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TMUX_VERSION: ${TMUX_VERSION:-3.6b}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
      cache_from:
        - type=gha,scope=tmux-static-build-arm64
      cache_to:
        - type=gha,mode=max,scope=tmux-static-build-arm64
    image: tmux-static-build-arm64
    platform: linux/arm64
    volumes:
      - ./bins/arm64:/output
    networks:
      - tmux_default

  tmux-static-build-arm32:
    container_name: tmux-static-build-arm32-${TMUX_VERSION:-3.6b}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TMUX_VERSION: ${TMUX_VERSION:-3.6b}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
      cache_from:
        - type=gha,scope=tmux-static-build-arm32
      cache_to:
        - type=gha,mode=max,scope=tmux-static-build-arm32
    image: tmux-static-build-arm32
    platform: linux/arm/v7
    volumes:
      - ./bins/arm32:/output
    networks:
      - tmux_default

networks:
  tmux_default: