name: Test Builders

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

permissions:
  contents: write

jobs:
  build:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      matrix:
        module:
          - postgre
          - netcat_traditional
          - nmap
          - vim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Clean Bins
        run: make clean-bins

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'

      - name: Install Dependencies
        run: |
          pip install python-on-whales
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run builder
        run: python3 main.py --single ${{ matrix.module }}
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1

      - name: Upload bins
        uses: actions/upload-artifact@v4
        with:
          name: bins-${{ matrix.module }}
          path: ${{ matrix.module }}/bins/
          retention-days: 1
